table fact_inventory
	lineageTag: 6367949b-327c-4e41-b943-e1468903d2a2

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: 42b895e7-0cbf-41b3-84a6-943f96175367
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column month
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ad7d7087-eede-4509-9284-7264227e8265
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column units
		dataType: int64
		formatString: 0
		lineageTag: 280b1e35-2ba5-4693-8441-9275f95c7161
		summarizeBy: sum
		sourceColumn: units

		annotation SummarizationSetBy = Automatic

	partition fact_inventory = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = inventory,
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductName", type text}, {"2025-01", Int64.Type}, {"2025-02", Int64.Type}, {"2025-03", Int64.Type}, {"2025-04", Int64.Type}, {"2025-05", Int64.Type}, {"2025-06", Int64.Type}, {"2025-07", Int64.Type}, {"2025-08", Int64.Type}, {"2025-09", Int64.Type}, {"2025-10", Int64.Type}, {"2025-11", Int64.Type}, {"2025-12", Int64.Type}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"ProductName"}, "Attribute", "Value"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Unpivoted Columns",{{"Attribute", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"ProductName"}, dim_product, {"product_name"}, "dim_product", JoinKind.LeftOuter),
				    #"Expanded dim_product" = Table.ExpandTableColumn(#"Merged Queries", "dim_product", {"product_key"}, {"dim_product.product_key"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded dim_product",{"dim_product.product_key", "ProductName", "Attribute", "Value"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"dim_product.product_key", "product_key"}, {"ProductName", "product_name"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"product_name"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Attribute", "month"}, {"Value", "units"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

