table fact_sales
	lineageTag: 0cb8c388-7934-413b-8946-69b17449f9a4

	column line_id
		dataType: string
		lineageTag: fc2fbd7e-e59b-4b8b-bc34-efadc3abe1c5
		summarizeBy: none
		sourceColumn: line_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: b9339283-2ebd-4765-bf9d-5ffa661ed34d
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: f0a44690-f8ab-4888-b69f-73e924ab2aff
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: 9f4ad0ae-0c25-46d7-90c0-e28c8f128b2e
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cost
		dataType: double
		lineageTag: fd120407-6ab0-424c-a629-d1cc5f438f3e
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discount_percentage
		dataType: double
		lineageTag: cc589d0b-9227-4c5f-89df-7ece9054fb72
		summarizeBy: sum
		sourceColumn: discount_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column line_total
		dataType: double
		lineageTag: 49186aa3-5165-4214-a710-7f206786c288
		summarizeBy: sum
		sourceColumn: line_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5cba55e5-4b87-4fe5-8dc7-704d779175b4
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 6f048be3-db9c-4e56-a050-b53cec0be1bd
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: 6669b501-a8ec-4754-948f-100b4eecb70e
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column flag_key
		dataType: int64
		formatString: 0
		lineageTag: 3aed25e7-dcd0-483b-91c7-a2d70f0c4b4f
		summarizeBy: none
		sourceColumn: flag_key

		annotation SummarizationSetBy = Automatic

	column ship_to_city_key
		dataType: int64
		formatString: 0
		lineageTag: 54e22dca-869d-4db4-95db-a513e1f9ee50
		summarizeBy: none
		sourceColumn: ship_to_city_key

		annotation SummarizationSetBy = Automatic

	column bill_to_city_key
		dataType: int64
		formatString: 0
		lineageTag: bf6f7aec-f4b3-472f-bf0d-cb9a66349912
		summarizeBy: none
		sourceColumn: bill_to_city_key

		annotation SummarizationSetBy = User

	hierarchy 'order_date Hierarchy'
		isHidden
		lineageTag: f8d09a0b-bb3f-40b2-aba4-7c268e2e2b60

		level order_date
			lineageTag: ebc33a6d-52a2-4d05-9337-4e56ee4fd1c0
			column: order_date

		changedProperty = IsHidden

	partition fact_sales = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = order_line_items,
				    #"Merged Queries" = Table.NestedJoin(Source, {"OrderID"}, orders, {"OrderID"}, "orders", JoinKind.LeftOuter),
				    #"Expanded orders" = Table.ExpandTableColumn(#"Merged Queries", "orders", {"CustomerName", "CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderDate", "OrderChannel", "Status", "Priority", "OrderTotal"}, {"orders.CustomerName", "orders.CustomerCity", "orders.RegionName", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "orders.OrderChannel", "orders.Status", "orders.Priority", "orders.OrderTotal"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded orders", {"orders.CustomerName"}, dim_customer, {"customer_name"}, "dim_customer", JoinKind.LeftOuter),
				    #"Expanded dim_customer" = Table.ExpandTableColumn(#"Merged Queries1", "dim_customer", {"customer_id"}, {"dim_customer.customer_id"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded dim_customer",{"LineID", "OrderID", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "dim_customer.customer_id", "orders.CustomerName", "orders.CustomerCity", "orders.RegionName", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "orders.OrderChannel", "orders.Status", "orders.Priority", "orders.OrderTotal"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Reordered Columns", {"ProductName"}, dim_product, {"product_name"}, "dim_products", JoinKind.LeftOuter),
				    #"Expanded dim_products" = Table.ExpandTableColumn(#"Merged Queries2", "dim_products", {"product_key"}, {"dim_products.product_key"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Expanded dim_products",{"LineID", "OrderID", "dim_products.product_key", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "dim_customer.customer_id", "orders.CustomerName", "orders.CustomerCity", "orders.RegionName", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "orders.OrderChannel", "orders.Status", "orders.Priority", "orders.OrderTotal"}),
				    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns1", each true),
				    #"Merged Queries3" = Table.NestedJoin(#"Filtered Rows", {"orders.OrderChannel", "orders.Status", "orders.Priority"}, dim_orders_flags, {"channel_code", "status", "priority"}, "dim_orders_flags", JoinKind.LeftOuter),
				    #"Expanded dim_orders_flags" = Table.ExpandTableColumn(#"Merged Queries3", "dim_orders_flags", {"flag_key"}, {"dim_orders_flags.flag_key"}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Expanded dim_orders_flags",{"LineID", "OrderID", "dim_products.product_key", "ProductName", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "dim_customer.customer_id", "orders.CustomerName", "orders.CustomerCity", "orders.RegionName", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "dim_orders_flags.flag_key", "orders.OrderChannel", "orders.Status", "orders.Priority", "orders.OrderTotal"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns2",{"orders.OrderChannel", "orders.Status", "orders.Priority", "ProductName", "orders.CustomerCity", "orders.RegionName"}),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Removed Columns",{"LineID", "OrderID", "dim_products.product_key", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "orders.OrderTotal", "dim_customer.customer_id", "orders.CustomerName", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "dim_orders_flags.flag_key"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns3",{"orders.OrderTotal"}),
				    #"Reordered Columns4" = Table.ReorderColumns(#"Removed Columns1",{"LineID", "OrderID", "dim_customer.customer_id", "orders.CustomerName", "dim_products.product_key", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "orders.ShipToCity", "orders.BillToCity", "orders.OrderDate", "dim_orders_flags.flag_key"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns4",{"orders.CustomerName"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Removed Columns2", {"orders.ShipToCity"}, dim_geo, {"city"}, "dim_geo", JoinKind.LeftOuter),
				    #"Expanded dim_geo" = Table.ExpandTableColumn(#"Merged Queries4", "dim_geo", {"geo_key"}, {"dim_geo.geo_key"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded dim_geo",{{"dim_geo.geo_key", "ship_to_city_key"}}),
				    #"Merged Queries5" = Table.NestedJoin(#"Renamed Columns", {"orders.BillToCity"}, dim_geo, {"city"}, "dim_geo", JoinKind.LeftOuter),
				    #"Expanded dim_geo1" = Table.ExpandTableColumn(#"Merged Queries5", "dim_geo", {"geo_key"}, {"dim_geo.geo_key"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded dim_geo1",{{"dim_geo.geo_key", "bill_to_city_key"}}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Renamed Columns1",{"orders.ShipToCity", "orders.BillToCity"}),
				    #"Reordered Columns5" = Table.ReorderColumns(#"Removed Columns3",{"LineID", "OrderID", "dim_customer.customer_id", "dim_products.product_key", "ship_to_city_key", "bill_to_city_key", "Quantity", "UnitPrice", "UnitCost", "DiscountPct", "LineTotal", "orders.OrderDate", "dim_orders_flags.flag_key"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns5",{{"dim_products.product_key", "product_key"}, {"dim_customer.customer_id", "customer_id"}, {"OrderID", "oder_id"}, {"LineID", "line_id"}, {"Quantity", "qantity"}, {"UnitPrice", "price"}, {"UnitCost", "cost"}, {"DiscountPct", "discount_percentage"}, {"LineTotal", "line_total"}, {"orders.OrderDate", "oder_date"}}),
				    #"Reordered Columns6" = Table.ReorderColumns(#"Renamed Columns2",{"line_id", "oder_id", "customer_id", "product_key", "dim_orders_flags.flag_key", "ship_to_city_key", "bill_to_city_key", "qantity", "price", "cost", "discount_percentage", "line_total", "oder_date"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns6",{{"dim_orders_flags.flag_key", "flag_key"}, {"qantity", "quantity"}, {"oder_date", "order_date"}, {"oder_id", "order_id"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns3",{{"order_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

