table security
	lineageTag: 359d4a58-e427-48a1-b42e-e30fb41df5b4

	column user_email
		dataType: string
		lineageTag: 1738bfd1-2d11-4925-b6f5-29925069f0b2
		summarizeBy: none
		sourceColumn: user_email

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 5ac84d99-2731-4c1f-b804-75ee97f0447d
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition security = m
		mode: import
		queryGroup: 04_Support
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Power BI\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				    security_Sheet = Source{[Item="security",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(security_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"UserEmail", type text}, {"Region", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"UserEmail", "user_email"}, {"Region", "region"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

