table dim_product
	lineageTag: 901bb266-456a-4229-bb94-083804b9ef7d

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: 56812db4-6b6c-4394-a499-dfc00c510ba3
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		lineageTag: e0dea6a4-c3e7-419a-bfb4-2edd34f1a213
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 6bce9d61-5f2c-47fb-8564-4a1c9f845888
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: d327013f-1c5e-49c1-8b57-2e7f0307fbc6
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		lineageTag: c6c882e5-12e0-442f-8f2b-4e253ac29b1e
		summarizeBy: none
		sourceColumn: subcategory

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: db02e1e7-ec1d-41fd-b362-52ae0f4c362b
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: 79627299-df9e-44c3-a6c8-e3ab88027b65
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column primary_supplier
		dataType: string
		lineageTag: 91f792f8-e667-4feb-aae3-2cf189949519
		summarizeBy: none
		sourceColumn: primary_supplier

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		queryGroup: 02_Dimensions
		source =
				let
				    Source = products,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ProductCode] <> "ELE-901" and [ProductCode] <> "HOM-902" and [ProductCode] <> "ZZZ-000")),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"SubcategoryName"}, subcategories, {"subcategory"}, "subcategories", JoinKind.LeftOuter),
				    #"Expanded subcategories" = Table.ExpandTableColumn(#"Merged Queries", "subcategories", {"category"}, {"subcategories.category"}),
				    #"Added Index" = Table.AddIndexColumn(#"Expanded subcategories", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "product_key"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"ProductDescription", "hash_key", "source_id"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"product_key", "ProductCode", "ProductName", "Brand", "SubcategoryName", "subcategories.category", "UnitPrice", "PrimarySupplier"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"ProductCode", "product_code"}, {"ProductName", "product_name"}, {"Brand", "brand"}, {"SubcategoryName", "subcategory"}, {"subcategories.category", "category"}, {"UnitPrice", "price"}, {"PrimarySupplier", "primary_supplier"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

