table dim_geo
	lineageTag: d38e9031-7d58-417f-a4e7-390c2ef8f929

	column geo_key
		dataType: int64
		formatString: 0
		lineageTag: 2cb5b048-957d-4073-a507-c7c27bfbb6a4
		summarizeBy: none
		sourceColumn: geo_key

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 326c2f1d-81e8-4d14-a44b-a85d528170c3
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: a074454b-b298-4b0c-a4b9-fa050c37447b
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition dim_geo = m
		mode: import
		queryGroup: 02_Dimensions
		source =
				let
				    Source = cities,
				    #"Removed Duplicates" = Table.Distinct(Source),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "CityName", "RegionName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "geo_key"}, {"CityName", "city"}, {"RegionName", "region"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

