table dim_customer
	lineageTag: fa1f87da-b319-4d3d-9682-990304705be0

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 3ffd33b0-03bf-4715-9234-efd70c4ceaf7
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: e9388a63-6bf9-4e76-b7a4-707c817862c3
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 5ff4ee3c-07a2-43d5-b059-6616c0c8525b
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column account_manager
		dataType: string
		lineageTag: 38d81016-4042-4778-9468-6605d6a43bb2
		summarizeBy: none
		sourceColumn: account_manager

		annotation SummarizationSetBy = Automatic

	column payment_terms
		dataType: string
		lineageTag: f012a125-7b21-43f4-9f9d-d50264037cff
		summarizeBy: none
		sourceColumn: payment_terms

		annotation SummarizationSetBy = Automatic

	column contact_name
		dataType: string
		lineageTag: 4fd9d97d-930d-4c0f-9ef4-6516c225b0a7
		summarizeBy: none
		sourceColumn: contact_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 8c988291-5ac0-4423-929e-af3f8d844c27
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: int64
		formatString: 0
		lineageTag: 84025818-220c-48c4-871c-129fefd9c560
		summarizeBy: sum
		sourceColumn: credit_limit

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 39544b13-6f9d-4976-a70a-848bdd82b87f
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column street
		dataType: string
		lineageTag: 35c72f22-d881-46d3-9730-984361760a7b
		summarizeBy: none
		sourceColumn: street

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 366d8dee-ee61-464a-8221-0700488b506a
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 589f0bf5-ebe1-4c1f-9a31-55f86e59ec66
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		queryGroup: 02_Dimensions
		source =
				let
				    Source = CUST_MASTER,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([CustomerID] <> 9999)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"CustomerID"}, customer_contacts, {"CustomerID"}, "customer_contacts", JoinKind.LeftOuter),
				    #"Expanded customer_contacts" = Table.ExpandTableColumn(#"Merged Queries", "customer_contacts", {"ContactName", "Email", "IsPrimary"}, {"customer_contacts.ContactName", "customer_contacts.Email", "customer_contacts.IsPrimary"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded customer_contacts", {"CustomerID"}, user_details, {"UserID"}, "user_details", JoinKind.LeftOuter),
				    #"Expanded user_details" = Table.ExpandTableColumn(#"Merged Queries1", "user_details", {"CreditLimit", "Phone"}, {"user_details.CreditLimit", "user_details.Phone"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded user_details", {"AddressID"}, Address, {"AddressID"}, "Address", JoinKind.LeftOuter),
				    #"Expanded Address" = Table.ExpandTableColumn(#"Merged Queries2", "Address", {"Street", "CityName"}, {"Address.Street", "Address.CityName"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded Address", {"Address.CityName"}, cities, {"CityName"}, "cities", JoinKind.LeftOuter),
				    #"Expanded cities" = Table.ExpandTableColumn(#"Merged Queries3", "cities", {"RegionName"}, {"cities.RegionName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded cities",{{"CustomerID", "customer_id"}, {"CustomerName", "customer_name"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"AddressID", "hash_key", "source_id", "customer_contacts.IsPrimary"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Segment", "segment"}, {"AccountManager", "account_manager"}, {"PaymentTerms", "payment_terms"}, {"customer_contacts.ContactName", "contact_name"}, {"customer_contacts.Email", "email"}, {"user_details.CreditLimit", "credit_limit"}, {"user_details.Phone", "phone"}, {"Address.Street", "street"}, {"Address.CityName", "city"}, {"cities.RegionName", "region"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

