table fact_promotion_coverage
	lineageTag: eaf38195-17bf-4a17-b8cc-65c9ecead6f1

	column campaign_key
		dataType: int64
		formatString: 0
		lineageTag: e9908395-21dc-45d1-8cac-cd2e0e918f36
		summarizeBy: none
		sourceColumn: campaign_key

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: bbd3c19c-b2d7-46ab-a273-461ca006c898
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	partition fact_promotion_coverage = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = campaign_skus,
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CampaignName", type text}, {"PromotedSKUs", type text}}),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Changed Type", {{"PromotedSKUs", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "PromotedSKUs"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"PromotedSKUs", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"PromotedSKUs", Text.Trim, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Trimmed Text", {"CampaignName"}, dim_campaign, {"campaing_name"}, "dim_campaign", JoinKind.LeftOuter),
				    #"Expanded dim_campaign" = Table.ExpandTableColumn(#"Merged Queries", "dim_campaign", {"campaign_key"}, {"dim_campaign.campaign_key"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded dim_campaign",{"dim_campaign.campaign_key", "CampaignName", "PromotedSKUs"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Reordered Columns", {"PromotedSKUs"}, dim_product, {"product_code"}, "dim_product", JoinKind.LeftOuter),
				    #"Expanded dim_product" = Table.ExpandTableColumn(#"Merged Queries1", "dim_product", {"product_key"}, {"dim_product.product_key"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Expanded dim_product",{"dim_campaign.campaign_key", "dim_product.product_key", "CampaignName", "PromotedSKUs"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns1",{"CampaignName", "PromotedSKUs"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"dim_campaign.campaign_key", "campaign_key"}, {"dim_product.product_key", "product_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

