table fact_order_process
	lineageTag: c9d9538b-0f02-4f9e-aa56-f3b1a5397eca

	column order_id
		dataType: string
		lineageTag: fb1543e5-877a-4487-98c0-5fae5785cdc5
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 9724793b-7cfd-4719-8ec1-32e7b783e65e
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 12f64e3b-5a94-4e89-ab25-39b6e4ee7662
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ship_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: dce4e66e-c0a1-4bc5-8d5b-b036e5676a56
		summarizeBy: none
		sourceColumn: ship_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column delivery_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 25642876-2ccd-4338-8af1-84bdcc35e60b
		summarizeBy: none
		sourceColumn: delivery_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column invoice_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 26b8f60e-2ba9-468b-a804-7dadec3a227b
		summarizeBy: none
		sourceColumn: invoice_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column pay_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 93a9a9ae-1797-428c-b764-f36c9b0f5725
		summarizeBy: none
		sourceColumn: pay_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column order_to_pay = DATEDIFF(fact_order_process[order_date], fact_order_process[pay_date], DAY)
		formatString: 0
		lineageTag: 22ea5bf4-cbad-4012-b3c6-7b3d819ee686
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fact_order_process = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = orders,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"CustomerName"}, dim_customer, {"customer_name"}, "dim_customer", JoinKind.LeftOuter),
				    #"Expanded dim_customer" = Table.ExpandTableColumn(#"Merged Queries", "dim_customer", {"customer_id"}, {"dim_customer.customer_id"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded dim_customer",{"OrderID", "dim_customer.customer_id", "CustomerName", "OrderDate"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns",{"CustomerName"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns1", {"OrderID"}, shipments, {"OrderID"}, "shipments", JoinKind.LeftOuter),
				    #"Expanded shipments" = Table.ExpandTableColumn(#"Merged Queries1", "shipments", {"ShipDate", "DeliveryDate"}, {"shipments.ShipDate", "shipments.DeliveryDate"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded shipments", {"OrderID"}, INVOICES, {"OrderID"}, "INVOICES", JoinKind.LeftOuter),
				    #"Expanded INVOICES" = Table.ExpandTableColumn(#"Merged Queries2", "INVOICES", {"InvoiceID", "InvoiceDate"}, {"INVOICES.InvoiceID", "INVOICES.InvoiceDate"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded INVOICES", {"INVOICES.InvoiceID"}, payments, {"InvoiceID"}, "payments", JoinKind.LeftOuter),
				    #"Expanded payments" = Table.ExpandTableColumn(#"Merged Queries3", "payments", {"PayDate"}, {"payments.PayDate"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Expanded payments",{"INVOICES.InvoiceID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns2",{{"OrderID", "order_id"}, {"dim_customer.customer_id", "customer_id"}, {"OrderDate", "order_date"}, {"shipments.ShipDate", "ship_date"}, {"shipments.DeliveryDate", "delivery_date"}, {"INVOICES.InvoiceDate", "invoice_date"}, {"payments.PayDate", "pay_date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"order_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

