table fasct_sales_targets
	lineageTag: 0f9d3efa-ae40-42b7-81be-c777558d301e

	column date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d9e8647f-64dc-44c1-812f-dc605fad4da8
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column target_revenue
		dataType: int64
		formatString: 0
		lineageTag: f12f9cf4-07c7-40fa-9993-7644896f6e1d
		summarizeBy: sum
		sourceColumn: target_revenue

		annotation SummarizationSetBy = Automatic

	partition fasct_sales_targets = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = sales_targets,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Period", "date"}, {"TargetRevenue", "target_revenue"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

